
-- MySQL Script generated by MySQL Workbench

-- PRACTICA_1 - APLICACIONES WEB

-- AUTORES: PATRICIA ORTIZ Y VICTOR CHAMIZO


SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;


--
-- DATABASE: `practica1_aw`
--

-- -----------------------------------------------------
-- Table `practica1_aw`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica1_aw`.`users` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `gender` TINYINT(4) NOT NULL,
  `score` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `practica1_aw`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica1_aw`.`friendship` (
  `user1` INT(11) NOT NULL,
  `user2` INT(11) NOT NULL,
  `request` TINYINT(4) NOT NULL DEFAULT '1',
  CONSTRAINT `fk_user1`
	FOREIGN KEY (`user1`) 
	REFERENCES `practica1_aw`.`users` (`idUser`)
	ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_user2`
	FOREIGN KEY (`user2`)
	REFERENCES `practica1_aw`.`users` (`idUser`)
	ON DELETE CASCADE ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;





